=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/Dashboard_1_0.dtd
<!ELEMENT Dashboard (#PCDATA | DashboardMatch | Description | Context | LayoutManager | Content)*>
<!ATTLIST Dashboard version CDATA #REQUIRED>
<!ATTLIST Dashboard name CDATA #REQUIRED>

<!ELEMENT DashboardMatch (#PCDATA | BeanMatch)*>
<!ATTLIST DashboardMatch type CDATA #REQUIRED>
<!ATTLIST DashboardMatch location CDATA #IMPLIED>

<!ELEMENT BeanMatch (#PCDATA | Condition)*>
<!ATTLIST BeanMatch id CDATA #REQUIRED>
<!ATTLIST BeanMatch type CDATA #REQUIRED>

<!ELEMENT Condition (#PCDATA)*>
<!ATTLIST Condition type CDATA #REQUIRED>
<!ATTLIST Condition filter CDATA #IMPLIED>
<!ATTLIST Condition attributeName CDATA #IMPLIED>
<!ATTLIST Condition value CDATA #IMPLIED>
<!ATTLIST Condition serverType CDATA #IMPLIED>


<!ELEMENT Context (#PCDATA)>
<!ATTLIST Context name CDATA #IMPLIED>
<!ATTLIST Context type CDATA #IMPLIED>
<!ATTLIST Context value CDATA #IMPLIED>

<!ELEMENT Attribute (#PCDATA | Component)*>
<!ATTLIST Attribute name CDATA #REQUIRED>
<!ATTLIST Attribute value CDATA #IMPLIED>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT Component (#PCDATA | Constraint | LayoutManager | Content | Attribute | Border)*>
<!ATTLIST Component id CDATA #IMPLIED>
<!ATTLIST Component type CDATA #REQUIRED>

<!ELEMENT Constraint (#PCDATA)>
<!ATTLIST Constraint anchor CDATA #IMPLIED>
<!ATTLIST Constraint gridx CDATA #IMPLIED>
<!ATTLIST Constraint gridy CDATA #IMPLIED>
<!ATTLIST Constraint widthx CDATA #IMPLIED>
<!ATTLIST Constraint weightx CDATA #IMPLIED>
<!ATTLIST Constraint weighty CDATA #IMPLIED>
<!ATTLIST Constraint fill CDATA #IMPLIED>
<!ATTLIST Constraint insets CDATA #IMPLIED>
<!ATTLIST Constraint type CDATA #REQUIRED>
<!ATTLIST Constraint direction CDATA #IMPLIED>

<!ELEMENT LayoutManager (#PCDATA)>
<!ATTLIST LayoutManager rows CDATA #IMPLIED>
<!ATTLIST LayoutManager cols CDATA #IMPLIED>
<!ATTLIST LayoutManager type CDATA #REQUIRED>
<!ATTLIST LayoutManager axis CDATA #IMPLIED>

<!ELEMENT Content (#PCDATA | Component)*>

<!ELEMENT Border (#PCDATA | Attribute)*>
<!ATTLIST Border type CDATA #REQUIRED>
<!ATTLIST Border color CDATA #IMPLIED>
<!ATTLIST Border thickness CDATA #IMPLIED>
<!ATTLIST Border top CDATA #IMPLIED>
<!ATTLIST Border left CDATA #IMPLIED>
<!ATTLIST Border bottom CDATA #IMPLIED>
<!ATTLIST Border right CDATA #IMPLIED>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/websphere/WebSphere_ServerDashboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<!--
    Created on : October 6, 2002, 10:01 PM
    Author     : ghinkl
-->

<Dashboard version="1.0" name="JBoss Server Dashboard">
  <Description>This dashboard displays basic information relating to the
    overall execution of a WebSphere server.</Description>

    <DashboardMatch type="Global" location="/WebSphere">
        <!--
        Example Object name:
        WebSphere:
            name=server1,
            process=server1,
            platform=common,
            node=gregh,
            j2eeType=J2EEServer,
            version=5.0,
            type=Server,
            mbeanIdentifier=cells/gregh/nodes/gregh/servers/server1/server.xml#Server_1,cell=gregh,
            processType=UnManagedProcess
        -->

        <BeanMatch id="ServerBean" type="Single">
            <Condition type="BeanObjectNameCondition" filter="WebSphere:"/>
            <Condition type="BeanObjectNameCondition" filter="type=Server"/>
        </BeanMatch>

        <!--
        Example Object name:
        WebSphere:
            name=JVM,
            process=server1,
            platform=common,
            node=gregh,
            j2eeType=JVM,
            J2EEServer=server1,
            version=6.0,
            type=JVM,
            mbeanIdentifier=JVM,
            cell=gregh
        -->
        <BeanMatch id="JVMBean" type="Single">
            <Condition type="BeanObjectNameCondition" filter="WebSphere:"/>
            <Condition type="BeanObjectNameCondition" filter="type=JVM"/>
        </BeanMatch>

    </DashboardMatch>


  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>
      <Component type="org.mc4j.console.dashboard.components.html.HtmlDashboardComponent">
          <Attribute name="htmlDocumentName" value="(Literal)WebSphere/WebSphere_ServerDashboard.html"/>

        <Content>




            <!--
            TODO GH: Doesn't work since IBM returns strings
            <Component id="memoryMeter" type="org.mc4j.console.dashboard.components.NumericAttributeGaugeMeter">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <Attribute name="beanNode" value="JVMBean"/>
                <Attribute name="maxAttributeName" value="(Literal)heapSize"/>
                <Attribute name="currentAttributeName" value="(Literal)freeMemory"/>
                <Attribute name="label" value="(Literal)Free Memory"/>
                <Attribute name="updateInterval" value="(Literal)1000"/>
                <Attribute name="warningPoint" value="(Literal)0.15"/>
                <Attribute name="criticalPoint" value="(Literal)0.05"/>
                <Attribute name="title" value="(Literal)Available Memory"/>
                <Attribute name="units" value="(Literal)MB"/>
                <Attribute name="opaque" value="(Literal)false"/>
                <Attribute name="unitConverter" value="(Literal)org.mc4j.console.util.unit.ByteToMegaByteConverter"/>
            </Component>
            -->

            <!--
            <Component id="memoryMeter" type="org.mc4j.console.dashboard.components.NumericAttributeMeter">
                <Attribute name="beanNode" value="JBossServerInfoBean"/>
                <Attribute name="preferredSize" value="(Literal)150,150"/>
                <Attribute name="maxAttributeName" value="(Literal)MaxMemory"/>
                <Attribute name="currentAttributeName" value="(Literal)FreeMemory"/>
                <Attribute name="minimumSize" value="(Literal)50,50"/>
                <Attribute name="label" value="(Literal)Free Memory"/>
                <Attribute name="updateInterval" value="(Literal)1000"/>

            </Component>


            <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                <Attribute name="beanNode" value="JBossServerInfoBean"/>
                <Constraint type="java.awt.GridBagConstraints" anchor="NORTH" gridx="1" gridy="2" widthx="2" weightx="0.5" weighty="0.5" fill="BOTH" insets="3,3,3,3"/>
                <Attribute name="preferredSize" value="(Literal)100,100"/>
                <Attribute name="attributeName" value="(Literal)FreeMemory"/>
            </Component>
            -->
        </Content>

      </Component>

  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/geronimo/Geronimo_ServerInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<!--
    Created on : October 6, 2002, 10:01 PM
    Author     : ghinkl
-->

<Dashboard version="1.0" name="Geronimo Server Info">
  <Description>This dashboard displays basic information relating to the
    overall execution of a Geronimo server.</Description>

    <DashboardMatch type="Global" location="/Geronimo">


        <BeanMatch id="GeronimoJ2EEServer" type="Single">
            <Condition type="BeanObjectNameCondition" filter="j2eeType=J2EEServer"/>
        </BeanMatch>



        <BeanMatch id="JVM" type="Single">
            <Condition type="BeanObjectNameCondition" filter="j2eeType=JVM"/>
        </BeanMatch>


        <BeanMatch id="GeronimoSystemInfo" type="Single">
            <Condition type="BeanObjectNameCondition" filter="geronimo.system:role=ServerInfo"/>
        </BeanMatch>


    </DashboardMatch>


  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>
      <Component type="org.mc4j.console.dashboard.components.html.HtmlDashboardComponent">
          <Attribute name="htmlDocumentName" value="(Literal)Geronimo/Geronimo_ServerInfo.html"/>

        <Content>



            <Component id="memoryMeter" type="org.mc4j.console.dashboard.components.NumericAttributeGaugeMeter">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <Attribute name="beanNode" value="JVM"/>
                <Attribute name="maxAttributeName" value="(Literal)maxMemory"/>
                <Attribute name="currentAttributeName" value="(Literal)freeMemory"/>
                <Attribute name="label" value="(Literal)Free Memory"/>
                <Attribute name="updateInterval" value="(Literal)1000"/>
                <Attribute name="warningPoint" value="(Literal)0.15"/>
                <Attribute name="criticalPoint" value="(Literal)0.05"/>
                <Attribute name="title" value="(Literal)Available Memory"/>
                <Attribute name="units" value="(Literal)MB"/>
                <Attribute name="opaque" value="(Literal)false"/>
                <Attribute name="unitConverter" value="(Literal)org.mc4j.console.util.unit.ByteToMegaByteConverter"/>
            </Component>

            <!--

            <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                <Attribute name="beanNode" value="JBossServerInfoBean"/>
                <Constraint type="java.awt.GridBagConstraints" anchor="NORTH" gridx="1" gridy="2" widthx="2" weightx="0.5" weighty="0.5" fill="BOTH" insets="3,3,3,3"/>
                <Attribute name="preferredSize" value="(Literal)100,100"/>
                <Attribute name="attributeName" value="(Literal)FreeMemory"/>
            </Component>
            -->
        </Content>

      </Component>

  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/jboss/JBoss_ServerInfo_Memory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<Dashboard version="1.0" name="JBoss Memory Meter">
  <Description>This dashboard displays basic information relating to the 
    overall execution of a JBoss server.</Description>

  <DashboardMatch type="Global" location="/JBoss">
      <BeanMatch id="JBossServerInfoBean" type="Single">
          <Condition type="BeanObjectNameCondition" filter="jboss.system:type=ServerInfo"/>
      </BeanMatch>
  </DashboardMatch>


    <!--
  <Context name="Match" type="java.lang.String" value="jboss.system:type=ServerInfo"/>
  -->
  
  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>
    
    <!-- *** The header section displays title and a refresh control *** -->
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <LayoutManager type="java.awt.BorderLayout"/>
        <Border type="javax.swing.border.EmptyBorder" top="(Literal)2" left="(Literal)5" bottom="(Literal)2" right="(Literal)5"/>
        <Content>
            <Component type="javax.swing.JPanel">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <LayoutManager type="java.awt.BorderLayout"/>
                <Content>
                    <Component type="javax.swing.JLabel" id="titleLable">
                        <Constraint type="BorderConstraints" direction="CENTER"/>
                        <Attribute name="text" value="DashboardName"/>
                        <Attribute name="font" value="(Literal)SansSerif bold 20"/>
                        <Attribute name="foreground" value="(Literal)0x666666"/>
                    </Component>
                    <Component type="javax.swing.JTextArea">
                        <Constraint type="BorderConstraints" direction="SOUTH"/>
                        <Attribute name="text" value="DashboardDescription"/>
                        <Attribute name="font" value="(Literal)DialogInput bold 14"/>
                        <Attribute name="opaque" value="(Literal)false"/>
                        <Attribute name="editable" value="(Literal)false"/>
                    </Component>
                </Content>
            </Component>
        </Content>
    </Component>
    

    <Component type="org.mc4j.console.dashboard.components.NumericAttributeGaugeMeter">
        <Constraint type="BorderConstraints" direction="CENTER"/>
        <Attribute name="beanNode" value="JBossServerInfoBean"/>
        <Attribute name="maxAttributeName" value="(Literal)MaxMemory"/>
        <Attribute name="currentAttributeName" value="(Literal)FreeMemory"/>
        <!--<Attribute name="minimumSize" value="(Literal)50,50"/>-->
        <Attribute name="label" value="(Literal)Free Memory"/>
        <Attribute name="updateInterval" value="(Literal)1000"/>
        <Attribute name="warningPoint" value="(Literal)0.2"/>
        <Attribute name="criticalPoint" value="(Literal)0.05"/>
        <Attribute name="title" value="(Literal)Available Memory"/>
        <Attribute name="units" value="(Literal)bytes"/>

    </Component>

  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/BasicMBean.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<!--
    Document   : BasicMBean.xml
    Created on : October 6, 2002, 10:01 PM
    Author     : ghinkl
    Description:
        Displays the basic information of an MBean
-->

<Dashboard version="1.0" name="Basic MBean View">
  <Description>Displays general information about any MBean in the system.</Description>

  <DashboardMatch type="Bean">
      <BeanMatch id="BeanNode" type="Single">
          <Condition type="BeanObjectNameCondition" filter=".*"/>
      </BeanMatch>
  </DashboardMatch>

  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>

    <!-- *** The header section displays title and a refresh control *** -->
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <LayoutManager type="java.awt.BorderLayout"/>
        <Border type="javax.swing.border.EmptyBorder" top="(Literal)2" left="(Literal)5" bottom="(Literal)2" right="(Literal)5"/>
        <Content>
            <Component type="javax.swing.JPanel">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <LayoutManager type="java.awt.BorderLayout"/>
                <Content>
                    <Component type="javax.swing.JLabel" id="titleLable">
                        <Constraint type="BorderConstraints" direction="CENTER"/>
                        <Attribute name="text" value="DashboardName"/>
                        <Attribute name="font" value="(Literal)SansSerif bold 20"/>
                        <Attribute name="foreground" value="(Literal)0x666666"/>
                    </Component>
                    <Component type="javax.swing.JTextArea">
                        <Constraint type="BorderConstraints" direction="SOUTH"/>
                        <Attribute name="text" value="(Message)General information about {ObjectName}"/>
                        <Attribute name="font" value="(Literal)DialogInput bold 14"/>
                        <Attribute name="opaque" value="(Literal)false"/>
                        <Attribute name="editable" value="(Literal)false"/>
                    </Component>
                </Content>
            </Component>
            <Component type="org.mc4j.console.dashboard.components.RefreshControlComponent">
                <Constraint type="BorderConstraints" direction="EAST"/>
                <Attribute name="refreshDelay" value="(Literal)30000"/>
            </Component>
        </Content>
    </Component>

    <!-- *** The main content is displayed within a scrollpane for easy viewing *** -->
    <Component type="javax.swing.JScrollPane">
        <Constraint type="BorderConstraints" direction="CENTER"/>
        <Attribute name="background" value="(Literal)0xFFFFFF"/>

        <Content>
            <Component type="javax.swing.JPanel">
                <Attribute name="background" value="(Literal)0xFFFFFF"/>

                <LayoutManager type="java.awt.BoxLayout" axis="Y_AXIS"/>
                <Content>
                    <!-- *** A Section holder is an included component for providing hide-able parts *** -->
                    <Component type="org.mc4j.console.swing.SectionHolder">
                    <Attribute name="title" value="(Literal)MBean Attributes"/>
                    <Attribute name="background" value="(Literal)0xFFFFFF"/>
                    <LayoutManager type="java.awt.BorderLayout"/>
                    <Content>

                        <!-- *** This component displays the attributes of an MBean *** -->
                        <Component type="org.mc4j.console.dashboard.components.AttributeTreeTableExplorer">
                            <!-- *** Notice were setting the node that we matched above by name here *** -->
                            <Attribute name="beanNode" value="BeanNode"/>
                            <Constraint type="BorderConstraints" direction="CENTER"/>
                            <Border type="javax.swing.border.LineBorder" color="(Literal)0x444444" thickness="(Literal)1"/>
                            <Attribute name="background" value="(Literal)0xFFFFFF"/>
                            <Attribute name="background" value="(Literal)0xFFFFFF"/>
                        </Component>
                    </Content>
                    </Component>
                    <Component type="org.mc4j.console.swing.SectionHolder">
                        <Attribute name="title" value="(Literal)MBean Operations"/>
                        <Attribute name="background" value="(Literal)0xFFFFFF"/>
                        <Content>
                            <Component type="org.mc4j.console.dashboard.components.OperationListComponent">
                                <Attribute name="beanNode" value="BeanNode"/>
                                <Attribute name="format" value="(Literal)FULL_FORMAT"/>
                            </Component>
                        </Content>
                    </Component>
                    <!--
                    <Component type="org.mc4j.console.dashboard.components.FillerComponent">
                        <Attribute name="type" value="(Literal)VERTICAL_GLUE_SHAPE"/>
                    </Component>
                    -->
                </Content>

            </Component>
        </Content>
    </Component>

  </Content>
</Dashboard>
