=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/Dashboard_1_0.dtd
<!ELEMENT Dashboard (#PCDATA | DashboardMatch | Description | Context | LayoutManager | Content)*>
<!ATTLIST Dashboard version CDATA #REQUIRED>
<!ATTLIST Dashboard name CDATA #REQUIRED>

<!ELEMENT DashboardMatch (#PCDATA | BeanMatch)*>
<!ATTLIST DashboardMatch type CDATA #REQUIRED>
<!ATTLIST DashboardMatch location CDATA #IMPLIED>

<!ELEMENT BeanMatch (#PCDATA | Condition)*>
<!ATTLIST BeanMatch id CDATA #REQUIRED>
<!ATTLIST BeanMatch type CDATA #REQUIRED>

<!ELEMENT Condition (#PCDATA)*>
<!ATTLIST Condition type CDATA #REQUIRED>
<!ATTLIST Condition filter CDATA #IMPLIED>
<!ATTLIST Condition attributeName CDATA #IMPLIED>
<!ATTLIST Condition value CDATA #IMPLIED>
<!ATTLIST Condition serverType CDATA #IMPLIED>


<!ELEMENT Context (#PCDATA)>
<!ATTLIST Context name CDATA #IMPLIED>
<!ATTLIST Context type CDATA #IMPLIED>
<!ATTLIST Context value CDATA #IMPLIED>

<!ELEMENT Attribute (#PCDATA | Component)*>
<!ATTLIST Attribute name CDATA #REQUIRED>
<!ATTLIST Attribute value CDATA #IMPLIED>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT Component (#PCDATA | Constraint | LayoutManager | Content | Attribute | Border)*>
<!ATTLIST Component id CDATA #IMPLIED>
<!ATTLIST Component type CDATA #REQUIRED>

<!ELEMENT Constraint (#PCDATA)>
<!ATTLIST Constraint anchor CDATA #IMPLIED>
<!ATTLIST Constraint gridx CDATA #IMPLIED>
<!ATTLIST Constraint gridy CDATA #IMPLIED>
<!ATTLIST Constraint widthx CDATA #IMPLIED>
<!ATTLIST Constraint weightx CDATA #IMPLIED>
<!ATTLIST Constraint weighty CDATA #IMPLIED>
<!ATTLIST Constraint fill CDATA #IMPLIED>
<!ATTLIST Constraint insets CDATA #IMPLIED>
<!ATTLIST Constraint type CDATA #REQUIRED>
<!ATTLIST Constraint direction CDATA #IMPLIED>

<!ELEMENT LayoutManager (#PCDATA)>
<!ATTLIST LayoutManager rows CDATA #IMPLIED>
<!ATTLIST LayoutManager cols CDATA #IMPLIED>
<!ATTLIST LayoutManager type CDATA #REQUIRED>
<!ATTLIST LayoutManager axis CDATA #IMPLIED>

<!ELEMENT Content (#PCDATA | Component)*>

<!ELEMENT Border (#PCDATA | Attribute)*>
<!ATTLIST Border type CDATA #REQUIRED>
<!ATTLIST Border color CDATA #IMPLIED>
<!ATTLIST Border thickness CDATA #IMPLIED>
<!ATTLIST Border top CDATA #IMPLIED>
<!ATTLIST Border left CDATA #IMPLIED>
<!ATTLIST Border bottom CDATA #IMPLIED>
<!ATTLIST Border right CDATA #IMPLIED>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/weblogic/Weblogic_ExecuteQueue_Stats.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<Dashboard version="1.0" name="Execute Queue Statistics">

  <Description>This dashboard shows the statistics of a WebLogic Execute Queue.</Description>
 
  <DashboardMatch type="Global" location="/Weblogic/Web">
      <BeanMatch id="ExecuteQueueRuntimeBean" type="Single">
          <Condition type="BeanObjectNameCondition" filter="Type=ExecuteQueueRuntime"/>
      </BeanMatch>
  </DashboardMatch>


  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>
    
    <!-- *** The header section displays title and a refresh control *** -->
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <LayoutManager type="java.awt.BorderLayout"/>
        <Border type="javax.swing.border.EmptyBorder" top="(Literal)2" left="(Literal)5" bottom="(Literal)2" right="(Literal)5"/>
        <Content>
            <Component type="javax.swing.JPanel">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <LayoutManager type="java.awt.BorderLayout"/>
                <Content>
                    <Component type="javax.swing.JLabel" id="titleLable">
                        <Constraint type="BorderConstraints" direction="CENTER"/>
                        <Attribute name="text" value="DashboardName"/>
                        <Attribute name="font" value="(Literal)SansSerif bold 20"/>
                        <Attribute name="foreground" value="(Literal)0x666666"/>
                    </Component>
                    <Component type="javax.swing.JTextArea">
                        <Constraint type="BorderConstraints" direction="SOUTH"/>
                        <Attribute name="text" value="DashboardDescription"/>
                        <Attribute name="font" value="(Literal)DialogInput bold 14"/>
                        <Attribute name="opaque" value="(Literal)false"/>
                        <Attribute name="editable" value="(Literal)false"/>
                    </Component>
                </Content>
            </Component>
        </Content>
    </Component>
    
    
    <!-- *** Scroll pane of info *** -->
    <Component type="javax.swing.JScrollPane">
            <Attribute name="background" value="(Literal)0xFFFFFF"/>
            <Content>
                <Component type="javax.swing.JPanel">
                    <Attribute name="background" value="(Literal)0xFFFFFF"/>
    
                    <Constraint type="BorderConstraints" direction="CENTER"/>
    
                    <Attribute name="preferredSize" value="100,100"/>
    
                    <LayoutManager type="java.awt.BoxLayout" axis="Y_AXIS"/>
                    <Content>
                        <Component type="org.mc4j.console.swing.SectionHolder">
                            <Attribute name="title" value="(Literal)Pending Requests"/>
                            <Attribute name="background" value="(Literal)0xFFFFFF"/>
                            <LayoutManager type="java.awt.GridLayout" rows="1" cols="1"/>
                            <Content>
                                <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                                    <Attribute name="beanNode" value="ExecuteQueueRuntimeBean"/>
                                    <Attribute name="preferredSize" value="(Literal)400,150"/>
                                    <Attribute name="attributeName" value="(Literal)PendingRequestCurrentCount"/>
                                 </Component>
                            </Content>
                        </Component>
                        <Component type="org.mc4j.console.swing.SectionHolder">
                            <Attribute name="title" value="(Literal)Requests Information"/>
                            <Attribute name="background" value="(Literal)0xFFFFFF"/>
                            <LayoutManager type="java.awt.GridLayout" rows="1" cols="1"/>
                            <Content>
                                <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                                    <Attribute name="beanNode" value="ExecuteQueueRuntimeBean"/>
                                    <Attribute name="preferredSize" value="(Literal)400,150"/>
                                    <Attribute name="attributeName" value="(Literal)ServicedRequestTotalCount"/>
                                 </Component>                          
                             </Content>
                        </Component>
                        <Component type="org.mc4j.console.swing.SectionHolder">
                            <Attribute name="title" value="(Literal)Requests Information"/>
                            <Attribute name="background" value="(Literal)0xFFFFFF"/>
                            <LayoutManager type="java.awt.GridLayout" rows="1" cols="1"/>
                            <Content>
                                <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                                    <Attribute name="beanNode" value="ExecuteQueueRuntimeBean"/>
                                    <Attribute name="preferredSize" value="(Literal)400,150"/>
                                    <Attribute name="attributeName" value="(Literal)ExecuteThreadCurrentIdleCount"/>
                                 </Component>                          
                             </Content>
                        </Component>
                        <Component type="org.mc4j.console.dashboard.components.FillerComponent">
                            <Attribute name="type" value="(Literal)VERTICAL_GLUE_SHAPE"/>
                        </Component>
                    </Content>
    
                </Component>
            </Content>
    </Component>
    
    
  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/weblogic/Weblogic_ServletTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<Dashboard version="1.0" name="Servlet Statistics">

  <Description>This dashboard shows the statistics of Weblogic Servlets.</Description>
 
  <DashboardMatch type="Global" location="/Weblogic/Web">
      <BeanMatch id="ServletRuntimeList" type="Multiple">
          <Condition type="BeanObjectNameCondition" filter="Type=ServletRuntime"/>
      </BeanMatch>
  </DashboardMatch>

  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>

    <!-- *** The header section displays title and a refresh control *** -->
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <LayoutManager type="java.awt.BorderLayout"/>
        <Border type="javax.swing.border.EmptyBorder" top="(Literal)2" left="(Literal)5" bottom="(Literal)2" right="(Literal)5"/>
        <Content>
            <Component type="javax.swing.JPanel">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <LayoutManager type="java.awt.BorderLayout"/>
                <Content>
                    <Component type="javax.swing.JLabel" id="titleLable">
                        <Constraint type="BorderConstraints" direction="CENTER"/>
                        <Attribute name="text" value="DashboardName"/>
                        <Attribute name="font" value="(Literal)SansSerif bold 20"/>
                        <Attribute name="foreground" value="(Literal)0x666666"/>
                    </Component>
                    <Component type="javax.swing.JTextArea">
                        <Constraint type="BorderConstraints" direction="SOUTH"/>
                        <Attribute name="text" value="DashboardDescription"/>
                        <Attribute name="font" value="(Literal)DialogInput bold 14"/>
                        <Attribute name="opaque" value="(Literal)false"/>
                        <Attribute name="editable" value="(Literal)false"/>
                    </Component>
                </Content>
            </Component>
            <Component type="org.mc4j.console.dashboard.components.RefreshControlComponent">
                <Constraint type="BorderConstraints" direction="EAST"/>
                <Attribute name="refreshDelay" value="(Literal)30000"/>
            </Component>
        </Content>
    </Component>


    <Component type="org.mc4j.console.dashboard.components.AttributeTableComponent">
        <Attribute name="beanList" value="ServletRuntimeList"/>
        <Constraint type="BorderConstraints" direction="CENTER"/>

        <Attribute name="background" value="(Literal)0xFFFFFF"/>
        <Attribute name="preferredSize" value="100,100"/>

        <Attribute name="AttributeName" value="(Literal)ServerRuntime"/>
        <Attribute name="AttributeName" value="(Literal)Name"/>
        <Attribute name="AttributeName" value="(Literal)ServletName"/>

        <Attribute name="AttributeName" value="(Literal)ExecutionTimeAverage"/>
        <Attribute name="AttributeName" value="(Literal)ExecutionTimeHigh"/>
        <Attribute name="AttributeName" value="(Literal)ExecutionTimeLow"/>
        <Attribute name="AttributeName" value="(Literal)ExecutionTimeTotal"/>
        <Attribute name="AttributeName" value="(Literal)InvocationTotalCount"/>

    </Component>


  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/jboss/JBoss_ServerInfoMBean.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<!--
    Created on : October 6, 2002, 10:01 PM
    Author     : ghinkl
-->

<Dashboard version="1.0" name="JBoss Server Info">
  <Description>This dashboard displays basic information relating to the
    overall execution of a JBoss server.</Description>

  <DashboardMatch type="Global" location="/JBoss">
      <BeanMatch id="JBossServerInfoBean" type="Single">
          <Condition type="BeanObjectNameCondition" filter="jboss.system:type=ServerInfo"/>
      </BeanMatch>
  </DashboardMatch>

  
  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>
    
    <!-- *** The header section displays title and a refresh control *** -->
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <LayoutManager type="java.awt.BorderLayout"/>
        <Border type="javax.swing.border.EmptyBorder" top="(Literal)2" left="(Literal)5" bottom="(Literal)2" right="(Literal)5"/>
        <Content>
            <Component type="javax.swing.JPanel">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <LayoutManager type="java.awt.BorderLayout"/>
                <Content>
                    <Component type="javax.swing.JLabel" id="titleLable">
                        <Constraint type="BorderConstraints" direction="CENTER"/>
                        <Attribute name="text" value="DashboardName"/>
                        <Attribute name="font" value="(Literal)SansSerif bold 20"/>
                        <Attribute name="foreground" value="(Literal)0x666666"/>
                    </Component>
                    <Component type="javax.swing.JTextArea">
                        <Constraint type="BorderConstraints" direction="SOUTH"/>
                        <Attribute name="text" value="DashboardDescription"/>
                        <Attribute name="font" value="(Literal)DialogInput bold 14"/>
                        <Attribute name="opaque" value="(Literal)false"/>
                        <Attribute name="editable" value="(Literal)false"/>
                    </Component>
                </Content>
            </Component>
            <Component type="org.mc4j.console.dashboard.components.RefreshControlComponent">
                <Constraint type="BorderConstraints" direction="EAST"/>
                <Attribute name="refreshDelay" value="(Literal)1000"/>
            </Component>
        </Content>
    </Component>
    
    <Component type="javax.swing.JSplitPane">
        <Constraint type="BorderConstraints" direction="CENTER"/>
        <Attribute name="orientation" value="(Literal)HORIZONTAL_SPLIT"/>
        <Attribute name="preferredSize" value="(Literal)400,300"/>
        <Attribute name="minimumSize" value="(Literal)400,300"/>
        <Attribute name="leftComponent">
        
            <Component type="javax.swing.JScrollPane">
                <Constraint type="java.awt.GridBagConstraints" anchor="NORTH" gridx="1" gridy="1" weightx="1" weighty="1" fill="BOTH"/>
                <Content>
                    <Component type="org.mc4j.console.dashboard.components.AttributeListComponent">
                        <Attribute name="beanNode" value="JBossServerInfoBean"/>
                        <!--Attribute name="MBeanNode" value="MBeanNode"/-->
                        <!--Attribute name="AttributeName" value="(Literal)BuildDate"/-->
                        <Attribute name="Label" value="(Literal)Server Information"/>
                        <Attribute name="background" value="(Literal)0xFFFFFF"/>

                        <Border type="javax.swing.border.TitledBorder">
                            <Attribute name="title" value="(Literal)MBean Attributes"/>
                        </Border>
                    </Component>
                 </Content>
            </Component>
        </Attribute>
        <Attribute name="rightComponent">
            <Component type="javax.swing.JPanel">
            
                <LayoutManager type="java.awt.GridBagLayout"/>
                
                <Content>
                    <Component type="javax.swing.JPanel">
                        <Constraint type="java.awt.GridBagConstraints" anchor="NORTH" gridx="1" gridy="1" weightx="0.5" weighty="0.5" fill="BOTH"/>
                        <Content>                                            
                            <Component type="org.mc4j.console.dashboard.components.NumericAttributeMeter">
                                <Attribute name="beanNode" value="JBossServerInfoBean"/>
                                <Attribute name="preferredSize" value="(Literal)150,150"/>
                                <Attribute name="maxAttributeName" value="(Literal)MaxMemory"/>
                                <Attribute name="currentAttributeName" value="(Literal)FreeMemory"/>
                                <Attribute name="minimumSize" value="(Literal)50,50"/>    
                                <Attribute name="label" value="(Literal)Free Memory"/>
                                <Attribute name="updateInterval" value="(Literal)1000"/>
                                
                            </Component>
                        </Content>
                    </Component>
                    <Component type="javax.swing.JPanel">
                        <Constraint type="java.awt.GridBagConstraints" anchor="NORTH" gridx="2" gridy="1" weightx="0.5" weighty="0.5" fill="BOTH"/>
                        <Content>                                            
                            <Component type="org.mc4j.console.dashboard.components.NumericAttributeMeter">
                                <Attribute name="beanNode" value="JBossServerInfoBean"/>
                                <Attribute name="preferredSize" value="(Literal)150,150"/>
                                <Attribute name="maxAttributeValue" value="(Literal)500"/>
                                <Attribute name="currentAttributeName" value="(Literal)ActiveThreadCount"/>
                                <Attribute name="minimumSize" value="(Literal)50,50"/>    
                                <Attribute name="label" value="(Literal)Active Threads"/>
                            </Component>
                        </Content>
                    </Component>
                    
                    <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                        <Attribute name="beanNode" value="JBossServerInfoBean"/>
                        <Constraint type="java.awt.GridBagConstraints" anchor="NORTH" gridx="1" gridy="2" widthx="2" weightx="0.5" weighty="0.5" fill="BOTH" insets="3,3,3,3"/>
                        <Attribute name="preferredSize" value="(Literal)100,100"/>
                        <Attribute name="attributeName" value="(Literal)FreeMemory"/>
                    </Component>
                    
                    <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                        <Attribute name="beanNode" value="JBossServerInfoBean"/>
                        <Constraint type="java.awt.GridBagConstraints" anchor="NORTH" gridx="2" gridy="2" widthx="2" weightx="0.5" weighty="0.5" fill="BOTH" insets="3,3,3,3"/>
                        <Attribute name="attributeName" value="(Literal)ActiveThreadCount"/>
                    
                    </Component>
                    
                    
                    
                </Content>
            </Component>
        
        </Attribute>
        
    </Component>
    
    <!-- List of methods to execute -->
    <Component type="org.mc4j.console.dashboard.components.OperationListComponent">
        <Attribute name="beanNode" value="JBossServerInfoBean"/> 
        <Constraint type="BorderConstraints" direction="SOUTH"/>
        <Attribute name="format" value="(Literal)BUTTON_ONLY_FORMAT"/>
        
        <Border type="javax.swing.border.TitledBorder">
            <Attribute name="title" value="(Literal)Server Actions"/>
        </Border>
    </Component>
    
  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/jboss/JBoss_System_Server_Control.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<!--
Author Greg Hinkle (ghinkle@users.sourceforge.net), May 2003
$Revision: 1.4 $($Author: ghinkl $ / $Date: 2004/04/16 15:49:47 $)
-->

<Dashboard version="1.0" name="JBoss Server Control">
  <Description>This dashboard has server control operations for JBoss.</Description>
 
  <DashboardMatch type="Global" location="/JBoss">
      <BeanMatch id="JBossServerNode" type="Single">
          <Condition type="BeanObjectNameCondition" filter="^jboss.system:type=Server$"/>
      </BeanMatch>
  </DashboardMatch>

  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>
    
    <!-- *** The header section displays title and a refresh control *** -->
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <LayoutManager type="java.awt.BorderLayout"/>
        <Border type="javax.swing.border.EmptyBorder" top="(Literal)2" left="(Literal)5" bottom="(Literal)2" right="(Literal)5"/>
        <Content>
            <Component type="javax.swing.JPanel">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <LayoutManager type="java.awt.BorderLayout"/>
                <Content>
                    <Component type="javax.swing.JLabel" id="titleLable">
                        <Constraint type="BorderConstraints" direction="CENTER"/>
                        <Attribute name="text" value="DashboardName"/>
                        <Attribute name="font" value="(Literal)SansSerif bold 20"/>
                        <Attribute name="foreground" value="(Literal)0x666666"/>
                    </Component>
                    <Component type="javax.swing.JTextArea">
                        <Constraint type="BorderConstraints" direction="SOUTH"/>
                        <Attribute name="text" value="DashboardDescription"/>
                        <Attribute name="font" value="(Literal)DialogInput bold 14"/>
                        <Attribute name="opaque" value="(Literal)false"/>
                        <Attribute name="editable" value="(Literal)false"/>
                    </Component>
                </Content>
            </Component>
        </Content>
    </Component>
    
    <Component type="javax.swing.JScrollPane">
        <Constraint type="BorderConstraints" direction="CENTER"/>
        
        <Content>
            <Component type="javax.swing.JPanel">
                <Content>
                    <Component type="org.mc4j.console.dashboard.components.OperationListComponent">
                        <Attribute name="beanNode" value="JBossServerNode"/>
                        <Attribute name="operationName" value="(Literal)runGarbageCollector"/>
                        <Attribute name="operationName" value="(Literal)exit"/>
                        <Attribute name="operationName" value="(Literal)halt"/>
                        <Attribute name="operationName" value="(Literal)shutdown"/>
                    </Component>
                </Content>
            </Component>
        </Content>
        
    </Component>
    
  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/jre15/JRE15_MemoryUsage_AreaChart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<Dashboard version="1.0" name="Pool Usage Area Chart">
  
  <Description>Memory usage chart of pools for a 1.5 JVM.</Description>
 
  <DashboardMatch type="Global" location="/JVM/Memory">
      <BeanMatch id="MemoryPools" type="Multiple">
          <Condition type="BeanObjectNameCondition" filter="type=MemoryPool"/>
      </BeanMatch>
  </DashboardMatch>

  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>
    
    <!-- *** The header section displays title and a refresh control *** -->
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <LayoutManager type="java.awt.BorderLayout"/>
        <Border type="javax.swing.border.EmptyBorder" top="(Literal)2" left="(Literal)5" bottom="(Literal)2" right="(Literal)5"/>
        <Content>
            <Component type="javax.swing.JPanel">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <LayoutManager type="java.awt.BorderLayout"/>
                <Content>
                    <Component type="javax.swing.JLabel" id="titleLable">
                        <Constraint type="BorderConstraints" direction="CENTER"/>
                        <Attribute name="text" value="DashboardName"/>
                        <Attribute name="font" value="(Literal)SansSerif bold 20"/>
                        <Attribute name="foreground" value="(Literal)0x666666"/>
                    </Component>
                    <Component type="javax.swing.JTextArea">
                        <Constraint type="BorderConstraints" direction="SOUTH"/>
                        <Attribute name="text" value="DashboardDescription"/>
                        <Attribute name="font" value="(Literal)DialogInput bold 14"/>
                        <Attribute name="opaque" value="(Literal)false"/>
                        <Attribute name="editable" value="(Literal)false"/>
                    </Component>
                </Content>
            </Component>
        </Content>
    </Component>
    
    <Component type="org.mc4j.jre15.components.MemoryUsageAreaChartComponent">
        <Attribute name="beanList" value="MemoryPools"/>
        <Attribute name="preferredSize" value="(Literal)400,250"/>
     </Component>

    
  </Content>
</Dashboard>
