=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/Dashboard_1_0.dtd
<!ELEMENT Dashboard (#PCDATA | DashboardMatch | Description | Context | LayoutManager | Content)*>
<!ATTLIST Dashboard version CDATA #REQUIRED>
<!ATTLIST Dashboard name CDATA #REQUIRED>

<!ELEMENT DashboardMatch (#PCDATA | BeanMatch)*>
<!ATTLIST DashboardMatch type CDATA #REQUIRED>
<!ATTLIST DashboardMatch location CDATA #IMPLIED>

<!ELEMENT BeanMatch (#PCDATA | Condition)*>
<!ATTLIST BeanMatch id CDATA #REQUIRED>
<!ATTLIST BeanMatch type CDATA #REQUIRED>

<!ELEMENT Condition (#PCDATA)*>
<!ATTLIST Condition type CDATA #REQUIRED>
<!ATTLIST Condition filter CDATA #IMPLIED>
<!ATTLIST Condition attributeName CDATA #IMPLIED>
<!ATTLIST Condition value CDATA #IMPLIED>
<!ATTLIST Condition serverType CDATA #IMPLIED>


<!ELEMENT Context (#PCDATA)>
<!ATTLIST Context name CDATA #IMPLIED>
<!ATTLIST Context type CDATA #IMPLIED>
<!ATTLIST Context value CDATA #IMPLIED>

<!ELEMENT Attribute (#PCDATA | Component)*>
<!ATTLIST Attribute name CDATA #REQUIRED>
<!ATTLIST Attribute value CDATA #IMPLIED>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT Component (#PCDATA | Constraint | LayoutManager | Content | Attribute | Border)*>
<!ATTLIST Component id CDATA #IMPLIED>
<!ATTLIST Component type CDATA #REQUIRED>

<!ELEMENT Constraint (#PCDATA)>
<!ATTLIST Constraint anchor CDATA #IMPLIED>
<!ATTLIST Constraint gridx CDATA #IMPLIED>
<!ATTLIST Constraint gridy CDATA #IMPLIED>
<!ATTLIST Constraint widthx CDATA #IMPLIED>
<!ATTLIST Constraint weightx CDATA #IMPLIED>
<!ATTLIST Constraint weighty CDATA #IMPLIED>
<!ATTLIST Constraint fill CDATA #IMPLIED>
<!ATTLIST Constraint insets CDATA #IMPLIED>
<!ATTLIST Constraint type CDATA #REQUIRED>
<!ATTLIST Constraint direction CDATA #IMPLIED>

<!ELEMENT LayoutManager (#PCDATA)>
<!ATTLIST LayoutManager rows CDATA #IMPLIED>
<!ATTLIST LayoutManager cols CDATA #IMPLIED>
<!ATTLIST LayoutManager type CDATA #REQUIRED>
<!ATTLIST LayoutManager axis CDATA #IMPLIED>

<!ELEMENT Content (#PCDATA | Component)*>

<!ELEMENT Border (#PCDATA | Attribute)*>
<!ATTLIST Border type CDATA #REQUIRED>
<!ATTLIST Border color CDATA #IMPLIED>
<!ATTLIST Border thickness CDATA #IMPLIED>
<!ATTLIST Border top CDATA #IMPLIED>
<!ATTLIST Border left CDATA #IMPLIED>
<!ATTLIST Border bottom CDATA #IMPLIED>
<!ATTLIST Border right CDATA #IMPLIED>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/carbon/Carbon_MemoryInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<!--
    Document   : BasicMBean.xml
    Created on : October 6, 2002, 10:01 PM
    Author     : ghinkl
    Description:
        Displays the basic information of an MBean
-->

<Dashboard version="1.0" name="Carbon Memory Info">
    <Description>This dashboard displays basic information relating to the 
    overall execution of the Carbon Framework.</Description>

  <DashboardMatch type="Global">
      <BeanMatch id="BeanNode" type="Single">
          <Condition type="BeanObjectNameCondition" filter="CarbonManagementComponent"/>
      </BeanMatch>
  </DashboardMatch>

    <LayoutManager type="java.awt.BorderLayout"/>
    <Content>

        <Component type="javax.swing.JPanel">
            <Constraint type="BorderConstraints" direction="NORTH"/>
            <!--LayoutManager type="java.awt.GridBagLayout"/-->
            <LayoutManager type="java.awt.GridLayout" rows="2" cols="1"/>
            <Content>
                <Component type="javax.swing.JLabel" id="titleLable">
                    <!--Constraint type="java.awt.GridBagConstraints" anchor="NORTHWEST" fill="HORIZONTAL" gridx="1" gridy="1"/-->
                    <Attribute name="text" value="(Literal)Carbon Management Dashboard"/>
                    <Attribute name="font" value="(Literal)Dialog bold 24"/>
                    <Attribute name="foreground" value="(Literal)0xFF2222"/>

                </Component>

                <Component type="javax.swing.JTextArea">
                    <!--Constraint type="java.awt.GridBagConstraints" anchor="NORTH" gridx="1" gridy="2"/-->
                    <Attribute name="text" value="(Literal)This Dashboard displays important information about the status of your Carbon Component Framework."/>
                    <Attribute name="opaque" value="(Literal)false"/>
                    <Attribute name="editable" value="(Literal)false"/>
                </Component>

            </Content>
        </Component>

        <Component type="javax.swing.JScrollPane">
            <Content>
                <Component type="javax.swing.JPanel">
                    <LayoutManager type="java.awt.BoxLayout" axis="Y_AXIS"/>

                    <Constraint type="BorderConstraints" direction="CENTER"/>
                    <Attribute name="background" value="(Literal)0xFFFFFF"/>
                    <Content>
                        <Component type="org.mc4j.console.swing.SectionHolder">
                            <Attribute name="title" value="(Literal)General Carbon Information"/>
                            <Attribute name="background" value="(Literal)0xFFFFFF"/>
                            <Content>
                                <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                                    <Attribute name="beanNode" value="BeanNode"/>
                                    <Constraint type="java.awt.GridBagConstraints" anchor="NORTH" gridx="1" gridy="2" widthx="2" weightx="0.5" weighty="0.5" fill="BOTH" insets="3,3,3,3"/>
                                    <Attribute name="preferredSize" value="(Literal)600,600"/>
                                    <Attribute name="updateInterval" value="(Literal)500"/>
                                    <Attribute name="attributeName" value="(Literal)FreeMemory"/>
                                </Component>
                            </Content>
                        </Component>
                        <Component type="org.mc4j.console.swing.SectionHolder">
                            <Attribute name="title" value="(Literal)General Carbon Information"/>
                            <Attribute name="background" value="(Literal)0xFFFFFF"/>
                            <Content>
                                <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                                    <Attribute name="beanNode" value="BeanNode"/>
                                    <Constraint type="java.awt.GridBagConstraints" anchor="NORTH" gridx="2" gridy="2" widthx="2" weightx="0.5" weighty="0.5" fill="BOTH" insets="3,3,3,3"/>
                                    <Attribute name="attributeName" value="(Literal)ActiveThreadCount"/>
                                </Component>
                            </Content>
                        </Component>
                    </Content>
                </Component>
            </Content>
        </Component>
    </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/carbon/Carbon_ConfigurationTree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<Dashboard version="1.0" name="Carbon Configuration Tree">

  <Description>This dashboard shows a tree view Carbon Configurations.</Description>

  <DashboardMatch type="Global">
      <BeanMatch id="BeanNode" type="Single">
          <Condition type="BeanObjectNameCondition" filter="type=org.sape.carbon.services.carbonmanagement.CarbonManagementService"/>
      </BeanMatch>
  </DashboardMatch>

  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>

    <!-- *** Header *** -->
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <LayoutManager type="java.awt.BorderLayout"/>
        <Content>
            <Component type="javax.swing.JLabel" id="titleLable">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <Attribute name="text" value="DashboardName"/>
                <Attribute name="font" value="(Literal)Dialog bold 24"/>
                <Attribute name="foreground" value="(Literal)0xFF2222"/>
            </Component>

            <Component type="org.mc4j.console.dashboard.components.RefreshControlComponent">
                <Constraint type="BorderConstraints" direction="EAST"/>
                <Attribute name="refreshDelay" value="(Literal)30000"/>
            </Component>

            <Component type="javax.swing.JTextArea">
                <Constraint type="BorderConstraints" direction="SOUTH"/>
                <Attribute name="text" value="DashboardDescription"/>
                <Attribute name="font" value="(Literal)Dialog bold 16"/>
                <Attribute name="opaque" value="(Literal)false"/>
                <Attribute name="editable" value="(Literal)false"/>
            </Component>

        </Content>
    </Component>



    <Component type="org.mc4j.carbon.config.tree.ConfigurationTreeComponent">
        <Constraint type="BorderConstraints" direction="CENTER"/>
        <Attribute name="background" value="(Literal)0xFFFFFF"/>

    </Component>


  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/jboss/JBoss_WebTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<Dashboard version="1.0" name="Web Component Statistics">
  
  <Description>This dashboard shows the statistics of a WebLogic Execute Queue.</Description>
    
  <DashboardMatch type="Global" location="/JBoss/Web" >
      <BeanMatch id="VHostList" type="Multiple">
          <Condition type="BeanObjectNameCondition" filter="vhost=localhost"/>
      </BeanMatch>
  </DashboardMatch>

  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>

    <!-- *** The header section displays title and a refresh control *** -->
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <LayoutManager type="java.awt.BorderLayout"/>
        <Border type="javax.swing.border.EmptyBorder" top="(Literal)2" left="(Literal)5" bottom="(Literal)2" right="(Literal)5"/>
        <Content>
            <Component type="javax.swing.JPanel">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <LayoutManager type="java.awt.BorderLayout"/>
                <Content>
                    <Component type="javax.swing.JLabel" id="titleLable">
                        <Constraint type="BorderConstraints" direction="CENTER"/>
                        <Attribute name="text" value="DashboardName"/>
                        <Attribute name="font" value="(Literal)SansSerif bold 20"/>
                        <Attribute name="foreground" value="(Literal)0x666666"/>
                    </Component>
                    <Component type="javax.swing.JTextArea">
                        <Constraint type="BorderConstraints" direction="SOUTH"/>
                        <Attribute name="text" value="DashboardDescription"/>
                        <Attribute name="font" value="(Literal)DialogInput bold 14"/>
                        <Attribute name="opaque" value="(Literal)false"/>
                        <Attribute name="editable" value="(Literal)false"/>
                    </Component>
                </Content>
            </Component>
            <Component type="org.mc4j.console.dashboard.components.RefreshControlComponent">
                <Constraint type="BorderConstraints" direction="EAST"/>
                <Attribute name="refreshDelay" value="(Literal)1000"/>
            </Component>
        </Content>
    </Component>


    <Component type="org.mc4j.console.dashboard.components.AttributeTableComponent">
        <Attribute name="beanList" value="VHostList"/>
        <Constraint type="BorderConstraints" direction="CENTER"/>

        <Attribute name="background" value="(Literal)0xFFFFFF"/>
        <Attribute name="preferredSize" value="100,100"/>

        <Attribute name="AttributeName" value="(Literal)vhost"/>
        <Attribute name="AttributeName" value="(Literal)context"/>
        <Attribute name="AttributeName" value="(Literal)Name"/>
        <Attribute name="AttributeName" value="(Literal)RequestCount"/>
        <Attribute name="AttributeName" value="(Literal)MinTime"/>
        <Attribute name="AttributeName" value="(Literal)MaxTime"/>
        <Attribute name="AttributeName" value="(Literal)ProcessingTime"/>
        <Attribute name="AttributeName" value="(Literal)ErrorCount"/>



    </Component>


  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/jboss/JBoss_Web_JettyNew.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">


<Dashboard version="1.0" name="JBoss Jetty Statistics">
  
  <Description>This dashboard shows the statistics of a Jetty servlet context.</Description>
 
  <DashboardMatch type="Global" location="/JBoss/Web" >
      <BeanMatch id="Jetty" type="Single">
          <Condition type="BeanObjectNameCondition" filter="^jboss.jetty:Server=0$"/>
      </BeanMatch>
  </DashboardMatch>

  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>
    
    <!-- *** The header section displays title and a refresh control *** -->
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <LayoutManager type="java.awt.BorderLayout"/>
        <Border type="javax.swing.border.EmptyBorder" top="(Literal)2" left="(Literal)5" bottom="(Literal)2" right="(Literal)5"/>
        <Content>
            <Component type="javax.swing.JPanel">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <LayoutManager type="java.awt.BorderLayout"/>
                <Content>
                    <Component type="javax.swing.JLabel" id="titleLable">
                        <Constraint type="BorderConstraints" direction="CENTER"/>
                        <Attribute name="text" value="DashboardName"/>
                        <Attribute name="font" value="(Literal)SansSerif bold 20"/>
                        <Attribute name="foreground" value="(Literal)0x666666"/>
                    </Component>
                    <Component type="javax.swing.JTextArea">
                        <Constraint type="BorderConstraints" direction="SOUTH"/>
                        <Attribute name="text" value="DashboardDescription"/>
                        <Attribute name="font" value="(Literal)DialogInput bold 14"/>
                        <Attribute name="opaque" value="(Literal)false"/>
                        <Attribute name="editable" value="(Literal)false"/>
                    </Component>
                </Content>
            </Component>
            <Component type="org.mc4j.console.dashboard.components.RefreshControlComponent">
                <Constraint type="BorderConstraints" direction="EAST"/>
                <Attribute name="refreshDelay" value="(Literal)1000"/>
            </Component>
        </Content>
    </Component>
    
    
    <!-- *** Scroll pane of info *** -->
    <Component type="javax.swing.JScrollPane">
            <Attribute name="background" value="(Literal)0xFFFFFF"/>
            <Content>
                <Component type="javax.swing.JPanel">
                    <Attribute name="background" value="(Literal)0xFFFFFF"/>
    
                    <Constraint type="BorderConstraints" direction="CENTER"/>
    
                    <Attribute name="preferredSize" value="100,100"/>
    
                    <LayoutManager type="java.awt.BoxLayout" axis="Y_AXIS"/>
                    <Content>
                        <Component type="org.mc4j.console.swing.SectionHolder">
                            <Attribute name="title" value="(Literal)Connection Information"/>
                            <Attribute name="background" value="(Literal)0xFFFFFF"/>
                            <LayoutManager type="java.awt.GridLayout" rows="1" cols="2"/>
                            <Content>
                                <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                                    <Attribute name="beanNode" value="Jetty"/>
                                    <Attribute name="preferredSize" value="(Literal)400,150"/>
                                    <Attribute name="attributeName" value="(Literal)connections"/>
                                    <Attribute name="attributeName" value="(Literal)connectionsOpen"/>
                                    <Attribute name="attributeName" value="(Literal)connectionsOpenMax"/>
                                    <Attribute name="attributeName" value="(Literal)connectionsRequestsAve"/>
                                    <Attribute name="attributeName" value="(Literal)connectionsRequestsMax"/>
                                 </Component>
                                 <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                                     <Attribute name="beanNode" value="Jetty"/>
                                     <Attribute name="preferredSize" value="(Literal)400,150"/>
                                     <Attribute name="attributeName" value="(Literal)connectionsDurationAve"/>
                                     <Attribute name="attributeName" value="(Literal)connectionsDurationMax"/>
                                 </Component>
                            </Content>
                        </Component>
                        <Component type="org.mc4j.console.swing.SectionHolder">
                            <Attribute name="title" value="(Literal)Requests Information"/>
                            <Attribute name="background" value="(Literal)0xFFFFFF"/>
                            <LayoutManager type="java.awt.GridLayout" rows="1" cols="2"/>
                            <Content>
                                <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                                    <Attribute name="beanNode" value="Jetty"/>
                                    <Attribute name="preferredSize" value="(Literal)400,150"/>
                                    <Attribute name="attributeName" value="(Literal)requests"/>
                                    <Attribute name="attributeName" value="(Literal)requestsActive"/>
                                    <Attribute name="attributeName" value="(Literal)requestsActiveMax"/>
                                 </Component>

                                <Component type="org.mc4j.console.dashboard.components.NumericAttributeGraph">
                                    <Attribute name="beanNode" value="Jetty"/>
                                    <Attribute name="preferredSize" value="(Literal)400,150"/>
                                    <Attribute name="attributeName" value="(Literal)requestsDurationAve"/>
                                    <Attribute name="attributeName" value="(Literal)requestsDurationMax"/>
                                 </Component>                            
                             </Content>
                        </Component>
                        <Component type="org.mc4j.console.dashboard.components.FillerComponent">
                            <Attribute name="type" value="(Literal)VERTICAL_GLUE_SHAPE"/>
                        </Component>
                    </Content>
    
                </Component>
            </Content>
    </Component>
    
    
  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/jre15/JRE15_ThreadTree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<Dashboard version="1.0" name="Threading">
  
  <Description>Live thread states and stacks.</Description>
 
  <DashboardMatch type="Global" location="/JVM">
      <BeanMatch id="MBeanNode" type="Single">
          <Condition type="BeanObjectNameCondition" filter="type=Threading"/>
      </BeanMatch>
  </DashboardMatch>

  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>
    
    <!-- *** The header section displays title and a refresh control *** -->
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <LayoutManager type="java.awt.BorderLayout"/>
        <Border type="javax.swing.border.EmptyBorder" top="(Literal)2" left="(Literal)5" bottom="(Literal)2" right="(Literal)5"/>
        <Content>
            <Component type="javax.swing.JPanel">
                <Constraint type="BorderConstraints" direction="CENTER"/>
                <LayoutManager type="java.awt.BorderLayout"/>
                <Content>
                    <Component type="javax.swing.JLabel" id="titleLable">
                        <Constraint type="BorderConstraints" direction="CENTER"/>
                        <Attribute name="text" value="DashboardName"/>
                        <Attribute name="font" value="(Literal)SansSerif bold 20"/>
                        <Attribute name="foreground" value="(Literal)0x666666"/>
                    </Component>
                    <Component type="javax.swing.JTextArea">
                        <Constraint type="BorderConstraints" direction="SOUTH"/>
                        <Attribute name="text" value="DashboardDescription"/>
                        <Attribute name="font" value="(Literal)DialogInput bold 14"/>
                        <Attribute name="opaque" value="(Literal)false"/>
                        <Attribute name="editable" value="(Literal)false"/>
                    </Component>
                </Content>
            </Component>
            <Component type="org.mc4j.console.dashboard.components.RefreshControlComponent">
                <Constraint type="BorderConstraints" direction="EAST"/>
                <Attribute name="refreshDelay" value="(Literal)1000"/>
            </Component>
        </Content>
    </Component>
    
    <Component type="org.mc4j.jre15.components.ThreadMBeanThreadBrowserComponent">
     </Component>
    
  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/HtmlDocumentTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<!--
    Document   : BasicMBean.xml
    Created on : October 6, 2002, 10:01 PM
    Author     : ghinkl
    Description:
        Displays the basic information of an MBean
-->

<Dashboard version="1.0" name="Html Document View">
  <Description>Uses html to lay out a dashboard.</Description>

  <DashboardMatch type="Bean">
      <BeanMatch id="BeanNode" type="Single">
          <Condition type="BeanObjectNameCondition" filter=".*"/>
      </BeanMatch>
  </DashboardMatch>

  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>


    <Component type="org.mc4j.console.dashboard.components.html.HtmlDashboardComponent">
        <Attribute name="htmlDocumentName" value="(Literal)HtmlDocumentTest.html"/>

        <Content>
            <Component id="attributeTable"  type="org.mc4j.console.dashboard.components.AttributeTreeTableExplorer">
                <!-- *** Notice were setting the node that we matched above by name here *** -->
                <Attribute name="beanNode" value="BeanNode"/>
                <Border type="javax.swing.border.LineBorder" color="(Literal)0x444444" thickness="(Literal)1"/>
                <Attribute name="background" value="(Literal)0xFFFFFF"/>
                <Attribute name="background" value="(Literal)0xFFFFFF"/>
            </Component>


        </Content>

    </Component>


  </Content>
</Dashboard>

=== TMJUSTNOW/MoocX/Mos/AdvancedJava/SYSTEM/ExternalToolOrLib/MONITORS/MC4J Console 1.2b8/dashboards/RelationsGraph2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dashboard PUBLIC "-//MC4J//DTD Dashboard 1.0//EN" "http://mc4j.sourceforge.net/Dashboard_1_0.dtd">

<!--
    Document   : BasicMBean.xml
    Created on : October 6, 2002, 10:01 PM
    Author     : ghinkl
    Description:
        Displays the basic information of an MBean
-->

<Dashboard version="1.0" name="Relations Graph2" >
  <Description>Displays a graph of the relations in the system.</Description>
  
  <DashboardMatch type="Bean">
      <BeanMatch id="RelationServiceBean" type="Single">
          <Condition type="BeanObjectNameCondition" filter="name=RelationService"/>
      </BeanMatch>
  </DashboardMatch>
  
  <LayoutManager type="java.awt.BorderLayout"/>
  <Content>
    
    
    
    <Component type="javax.swing.JPanel">
        <Constraint type="BorderConstraints" direction="NORTH"/>
        <!--LayoutManager type="java.awt.GridBagLayout"/-->
        <LayoutManager type="java.awt.GridLayout" rows="2" cols="1"/>
        <Content>
            <Component type="javax.swing.JLabel" id="titleLable">
                <!--Constraint type="java.awt.GridBagConstraints" anchor="NORTHWEST" fill="HORIZONTAL" gridx="1" gridy="1"/-->
                <Attribute name="text" value="(Literal)Relationship graph2"/>
                <Attribute name="font" value="(Literal)Dialog bold 24"/>
                <Attribute name="foreground" value="(Literal)0xFF2222"/>

            </Component>

            <Component type="javax.swing.JTextArea">
                <!--Constraint type="java.awt.GridBagConstraints" anchor="NORTH" gridx="1" gridy="2"/-->
                <Attribute name="text" value="(Literal)This Dashboard displays a graph of the relations in the system."/>
                <Attribute name="opaque" value="(Literal)false"/>
            </Component>

        </Content>
    </Component>

    
    
    <Component type="org.mc4j.console.dashboard.components.RelationsGraphComponent4">
        <Attribute name="beanNode" value="RelationServiceBean"/>
        <Constraint type="BorderConstraints" direction="CENTER"/>
        <Attribute name="background" value="(Literal)0xFFFFFF"/>
        <Attribute name="background" value="(Literal)0xFFFFFF"/>
                
        <Attribute name="preferredSize" value="(Literal)600,600"/>
        <Attribute name="size" value="(Literal)600,600"/>                
    </Component>

  </Content>
</Dashboard>
